### ISSUE TITLE
Verification Issues

### ISSUE THREAD

**Issue by StaticGamer** [zklm/ssherder-issues#16]
While I was making an account in SS Herder there was a problem resulting in me not getting a verification email, making myself unable to reuse the same email and user name. My concern is that while there is a message saying to contact the maker there is no clear place that provides this contact information. Which is why I am making this.
I wonder if it would be possible to add the ability to resend the verification email so it can be re sent if the email was not received, and as a backup have the contact information on the same page that says that the creator should be contacted if it is not received in a few minutes. It is the first page seen when logging in when the email is not verified, so it would make things a lot easier for some people.

**Comment by zklm** [comment]
Agreed. I also really need to work on better email delivery. Looking at the records, live/hotmail delivery has been really terrible.

**Comment by zklm** [comment]
For now I've made it so accounts with unverified email addresses can log in as usual. 

Internally, verification status is still tracked just in case there are any features which need to be restricted to verified users only, to prevent abuse.
