### ISSUE TITLE
My Material (Add more options)

### ISSUE THREAD

**Issue by I3lackBro** [zklm/ssherder-issues#18]
>When selecting material there is no option to select 3*, 4* and 6* penguins.
There is also no option for 3* and 4* swirlies.
>Missing option for:
       Neris and Evolved Neris
       Littre and Littre- Evolved 
       Mera and Mera- Evolved
       Kurma and Kurma- Evolved
       Beezlzebub and Beezlzebub- Evolved

**Comment by zklm** [comment]
I'm not too sure if I want to add in gatekeepers and swirlies. The materials section is currently just for tracking evolutions.
