### ISSUE TITLE
EE Lynia Secondary Stats

### ISSUE THREAD

**Issue by I3lackBro** [zklm/ssherder-issues#19]
If you change her Primary Stats level from 1 to any other level above that her Reflexes decrease which does not make sense.
![lynia 1](https://cloud.githubusercontent.com/assets/19802517/15868310/4fef5aa6-2cb5-11e6-970b-6bf5c715c3ed.PNG)
![lynia](https://cloud.githubusercontent.com/assets/19802517/15868311/4ff043d0-2cb5-11e6-89ee-c9457be0b4e9.PNG)

**Comment by LostTwo** [comment]
Actually, some characters have decreasing reflex. Example: lv.1 Anael vs. lv.50 Anael

[Here's another database to prove it](http://soccerspirits.enygmatic.net/#/characters/details/31214)

**Comment by zklm** [comment]
Isn't that expected?

Players in-game will actually have a declining reflex stat the more they're leveled (I think the reason they do this is referencing how players will lose have declining reflexes the older they become).
