### ISSUE TITLE
[Suggestion]  Reverse Chains Search

### ISSUE THREAD

**Issue by LostTwo** [zklm/ssherder-issues#20]
So... One thing that I used the site for was to search for chains. Before the overhaul, it was just a search away. For example, during Robin's recall, this helped me pinpoint his (Robin-only) chains on other characters, before recalling him. 

Now that Luka, Gerrard and Silla are up for recall, I'd hope to be able to do that again.

**Comment by zklm** [comment]
I really need to get on that. Shouldn't be too long before I add complex searching/filtering in the characters section.

**Comment by zklm** [comment]
Finally implemented, still some quirks to fix up but it's functional

[Characters Section](https://ssherder.com/characters/)
