### ISSUE TITLE
Only 5 and 6* showing up

### ISSUE THREAD

**Issue by jdschmi1** [zklm/ssherder-issues#24]
I had all my 3 and 4*s also in my collection but I cannot see them and I have checked and all the filters and everything are set to default/off.

**Comment by zklm** [comment]
Fixed, sorry about that.

In the past every character had a season value of 1 or 2. After the patch, 1=Classic, 2=New, so they changed around a lot of them, but they also gave all 2* to 4* players and managers a season value of 0. The filter system was then only showing characters which had a season value of 1 or 2.
