### ISSUE TITLE
Superb Boss Data

### ISSUE THREAD

**Issue by f3rd1** [zklm/ssherder-issues#28]
Hi Zklm.

I'm not sure where to ask this, so I wrote it as an issue here.

In the timeline, just noticed that Alice is not appearing anywhere in the timeline.
So, is the Superb Boss added according to their first appearance, or their reappearance?

Thank you.

Regards,
-FF

**Comment by zklm** [comment]
Should be on first appearance, just made a mistake and forgot to include her, will fix in next update

**Comment by f3rd1** [comment]
Thanks Zklm.
I'll mark this as closed yah.
